import Head from "next/head";
import useRandomNum from "@/hooks/useRandomNum";
import { useState } from "react";
import Image from "next/image";
import styles from '../styles/index.module.css'
export default function Home() {
  const [character, setCharacter] = useState(null);
  const [error, setError] = useState(null);
  const [isPending, setIspending] = useState(false);
  const characterId = useRandomNum(1, 826);
const loader =()=>{
  return`https://rickandmortyapi.com/api/character/avatar/${characterId}.jpeg`
}
console.log(loader)
  const handleClick = async (id) => {
    try {
      id = characterId;
      setError(null);
      setIspending(true);
      setCharacter(null);
      const response = await fetch(`https://rickandmortyapi.com/api/character/${id}`);
      console.log(response)
      const jsonResponse = await response.json();
      
      console.log(jsonResponse);
      setIspending(false);
      setCharacter(jsonResponse);
    } catch (error) {
      setError(error);
      setIspending(false);
      setCharacter(null);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Random Rick and Morty character! </h1>

        <button  className={styles.button} onClick={handleClick}>show me a new character</button>
        {error && <p>{error}</p>}
        {isPending && <p>Loading...</p>}

        {character && (
          <section className={styles.character}>
            <Image loader={loader} src={character.image} alt="character's image" width={300} height={300} className={styles.image} />
            <div className="infoCharacter">
              <h2>Name:{character.name}</h2>
              <p>Gender:{character.gender}</p>
              <p>Type:{character.type}</p>
              <p>Species:{character.species}</p>
              <p>Status:{character.status}</p>
              <p>Id:{character.id}</p>
            </div>
          </section>
        )}
      </main>
    </div>
  );
}
